import { GoogleOAuthProvider } from '@react-oauth/google';
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      
<GoogleOAuthProvider clientId='1077512729862-c5rvioghn5gretuli7upl9j7dk1ch6no.apps.googleusercontent.com'>

        {children}
</GoogleOAuthProvider>
      </body>
    </html>
  );
}
